Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # ou "ubuntu/focal64" si tu préfères Ubuntu 20.04
  config.vm.hostname = "datalake-vm"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y openjdk-11-jdk curl wget git net-tools
  SHELL
end
